/**
 * test-cli-plugin Plugin
 * Generated by Plugin CLI Tool
 */

class TestCliPluginPlugin {
  constructor(context) {
    this.context = context;
    this.logger = context.logger;
    this.pluginName = context.pluginName;
  }

  // Lifecycle methods
  async onInstall() {
    this.logger.info(`Plugin ${this.pluginName} installed`);
  }

  async onEnable() {
    this.logger.info(`Plugin ${this.pluginName} enabled`);
  }

  async onDisable() {
    this.logger.info(`Plugin ${this.pluginName} disabled`);
  }

  async onUninstall() {
    this.logger.info(`Plugin ${this.pluginName} uninstalled`);
  }

  // Add your plugin methods here
}

module.exports = TestCliPluginPlugin;